spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: guoxin
    url: jdbc:mysql:///springboot_jdbc
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
